-- public.login_attempts definition

-- Drop table

-- DROP TABLE public.login_attempts;

CREATE TABLE public.login_attempts (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	identifier text NOT NULL,
	ip_address inet NOT NULL,
	attempts int4 DEFAULT 1 NULL,
	last_attempt_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT login_attempts_identifier_ip_address_key UNIQUE (identifier, ip_address),
	CONSTRAINT login_attempts_pkey PRIMARY KEY (id)
);


-- public.offices definition

-- Drop table

-- DROP TABLE public.offices;

CREATE TABLE public.offices (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" text NOT NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT offices_pkey PRIMARY KEY (id)
);


-- public.password_recovery_attempts definition

-- Drop table

-- DROP TABLE public.password_recovery_attempts;

CREATE TABLE public.password_recovery_attempts (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	email text NOT NULL,
	attempted_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT password_recovery_attempts_pkey PRIMARY KEY (id)
);


-- public.clients definition

-- Drop table

-- DROP TABLE public.clients;

CREATE TABLE public.clients (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" text NOT NULL,
	"document" text NOT NULL,
	contact text NULL,
	address text NULL,
	is_recurrent bool DEFAULT false NULL,
	recurrence_value numeric(12, 2) NULL,
	recurrence_day int4 NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	deleted_at timestamp NULL,
	office_id int4 NOT NULL,
	CONSTRAINT clients_pkey PRIMARY KEY (id),
	CONSTRAINT fk_clients_offices FOREIGN KEY (office_id) REFERENCES public.offices(id)
);
CREATE UNIQUE INDEX clients_document_idx ON public.clients USING btree (document, office_id);
CREATE INDEX idx_clients_office_id ON public.clients USING btree (office_id);


-- public.office_expenses definition

-- Drop table

-- DROP TABLE public.office_expenses;

CREATE TABLE public.office_expenses (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	description text NOT NULL,
	amount numeric(12, 2) NOT NULL,
	due_date date NOT NULL,
	status text DEFAULT 'Pendente'::text NULL,
	is_recurrent bool DEFAULT false NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	deleted_at timestamp NULL,
	office_id int4 NOT NULL,
	CONSTRAINT office_expenses_pkey PRIMARY KEY (id),
	CONSTRAINT office_expenses_offices_fk FOREIGN KEY (office_id) REFERENCES public.offices(id)
);


-- public.processes definition

-- Drop table

-- DROP TABLE public.processes;

CREATE TABLE public.processes (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	client_id int4 NOT NULL,
	process_number text NOT NULL,
	tribunal text NULL,
	"target" text NULL,
	description text NULL,
	status text DEFAULT 'Ativo'::text NULL,
	value_charged numeric(12, 2) DEFAULT 0.00 NULL,
	payment_method text NULL,
	em_conta_details text NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	deleted_at timestamp NULL,
	office_id int4 NOT NULL,
	CONSTRAINT processes_pkey PRIMARY KEY (id),
	CONSTRAINT fk_processes_clients FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE CASCADE,
	CONSTRAINT fk_processes_offices FOREIGN KEY (office_id) REFERENCES public.offices(id)
);
CREATE INDEX idx_processes_office_id ON public.processes USING btree (office_id);


-- public.services definition

-- Drop table

-- DROP TABLE public.services;

CREATE TABLE public.services (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	client_id int4 NOT NULL,
	description text NOT NULL,
	value_charged numeric(12, 2) DEFAULT 0.00 NOT NULL,
	payment_method text NULL,
	em_conta_details text NULL,
	status text DEFAULT 'Pendente'::text NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	deleted_at timestamp NULL,
	office_id int4 NOT NULL,
	CONSTRAINT services_pkey PRIMARY KEY (id),
	CONSTRAINT fk_services_clients FOREIGN KEY (client_id) REFERENCES public.clients(id),
	CONSTRAINT fk_services_offices FOREIGN KEY (office_id) REFERENCES public.offices(id)
);
CREATE INDEX idx_services_office_id ON public.services USING btree (office_id);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	username text NOT NULL,
	email text NOT NULL,
	"password" text NOT NULL,
	avatar_url text NULL,
	"name" text NOT NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	office_id int4 NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT users_offices_fk FOREIGN KEY (office_id) REFERENCES public.offices(id)
);


-- public.financial_movements definition

-- Drop table

-- DROP TABLE public.financial_movements;

CREATE TYPE public."financial_movement_type" AS ENUM (
	'charge',
	'payment');

CREATE TABLE public.financial_movements (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	process_id int4 NULL,
	"type" public."financial_movement_type" NOT NULL,
	amount numeric(12, 2) NOT NULL,
	description text NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	client_id int4 NULL,
	service_id int4 NULL,
	movement_date timestamp NULL,
	office_id int4 NOT NULL,
	CONSTRAINT financial_movements_one_entry_check CHECK ((((
CASE
    WHEN (service_id IS NOT NULL) THEN 1
    ELSE 0
END +
CASE
    WHEN (process_id IS NOT NULL) THEN 1
    ELSE 0
END) +
CASE
    WHEN (client_id IS NOT NULL) THEN 1
    ELSE 0
END) = 1)),
	CONSTRAINT financial_movements_pkey PRIMARY KEY (id),
	CONSTRAINT financial_movements_clients_fk FOREIGN KEY (client_id) REFERENCES public.clients(id),
	CONSTRAINT financial_movements_services_fk FOREIGN KEY (service_id) REFERENCES public.services(id),
	CONSTRAINT fk_financial_movements_office FOREIGN KEY (office_id) REFERENCES public.offices(id),
	CONSTRAINT fk_financial_movements_processes_2 FOREIGN KEY (process_id) REFERENCES public.processes(id) ON DELETE CASCADE
);
CREATE INDEX financial_movements_office_id_idx ON public.financial_movements USING btree (office_id, movement_date);


-- public.password_recovery_tokens definition

-- Drop table

-- DROP TABLE public.password_recovery_tokens;

CREATE TABLE public.password_recovery_tokens (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int4 NOT NULL,
	"token" text NOT NULL,
	expires_at timestamp NOT NULL,
	CONSTRAINT password_recovery_tokens_pkey PRIMARY KEY (id),
	CONSTRAINT password_recovery_tokens_token_key UNIQUE (token),
	CONSTRAINT password_recovery_tokens_users_fk FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE INDEX idx_password_recovery_tokens_token ON public.password_recovery_tokens USING btree (token);